
// Weather section

export const WEATHER_FETCH_REQUESTED = 'WEATHER_FETCH_REQUESTED';
export const WEATHER_FETCH_SUCCEEDED = 'WEATHER_FETCH_SUCCEEDED';
export const WEATHER_FETCH_FAILED = 'WEATHER_FETCH_FAILED';
export const WEATHER_TOGGLE_TEMPERATURE = 'WEATHER_TOGGLE_TEMPERATURE';